### ISSUE TITLE
Authtoken is not refreshed on ping timeout

### ISSUE THREAD

**Issue by kryogenic** [d-fischer/twitch#161] opened 2020-08-02 12:55 UTC
### Code

```
[2020-08-02T03:23:51.200Z] ⚠️  ircv3 WARNING Reconnecting because the last ping took over 10 seconds
[2020-08-02T03:23:59.251Z] ℹ️  ircv3 INFO Disconnected
[2020-08-02T03:23:59.255Z] ℹ️  ircv3 INFO Connecting to irc-ws.chat.twitch.tv:443
[2020-08-02T03:24:00.903Z] ℹ️  ircv3 INFO Connection to server irc-ws.chat.twitch.tv:443 established
[2020-08-02T03:24:01.841Z] ℹ️  ircv3 INFO Disconnected
```

### Expected behavior

IRC Client should check if the token is expired and refresh it before reconnecting

### Actual Behavior

IRC Client tries to reconnect using the old authtoken and fails

### Environment

- Version: 4.2.0-pre.4
- Node version: v14.5.0
- Operating system: Linux

**Comment by d-fischer** [comment] 2020-10-01 21:08
This should be fixed with ircv3 0.26.1. Please update the package deep in your tree (removing it from your lockfile manually, then reinstalling, should upgrade it most cleanly without touching any other packages) and give me some feedback before I make the new patch version a hard dependency of the `twitch-chat-client` package.

**Comment by d-fischer** [comment] 2020-10-20 16:30
Closing for the time being - please report back if you still experience this issue.

**Comment by cheeseandcereal** [comment] 2020-10-30 04:52
I don't think this issue is fixed. I experienced the same thing with v4.2.6 using a deep-updated ircv3 chat client v0.26.4

I believe the fundamental problem stems from this line: https://github.com/d-fischer/twitch/blob/9b7a79a1801d7747f51e8e8f398f454b3483cffd/packages/twitch-chat-client/src/ChatClient.ts#L1378

Upon receiving this auth issue, it does a manual disconnect call on the underlying connection, causing it to stop retrying to reconnect (even if re-connection is enabled and its using a `PersistentConnection`).

We can see this issue happening because the implemented `getPassword` function will always assume the password it has is correct if it has _ever_ been used to successfully authenticate before: https://github.com/d-fischer/twitch/blob/9b7a79a1801d7747f51e8e8f398f454b3483cffd/packages/twitch-chat-client/src/ChatClient.ts#L2125

This is a bad assumption to make because a password that was valid 2 weeks ago is likely no longer valid if it has to reconnect.

The flow which reproduces this is something like this:

1. Client is created, new credentials are fetched and saved/used to register with the connected twitch IRC server
1. Twitch IRC server responds successfully, validating the auth saved on the client
1. At some point, the previously used irc password (auth token) expires while the client is still connected to irc
1. At some point after token expiration, the irc client disconnects for any reason and attempts to reconnect
1. Upon reconnecting, the irc client calls `getPassword`, which uses the previously cached (and expired) password which it assumes still works
1. The twitch irc server rejects these expired credentials, triggering the 'case undefined' auth failure, sending an `onAuthenticationFailure` event, and manually disconnecting the IRC connection, causing it to never try to reconnect
1. The twitch irc client never reconnects because the auth failure caused a manual disconnection without a new connection attempt

**Comment by d-fischer** [comment] 2020-11-01 20:55
I will reinvestigate this. Maybe also serves as a reminder to test more failing cases in general.

**Comment by cheeseandcereal** [comment] 2020-11-02 05:52
This is pretty easily reproducible without waiting with something like the following code:

```ts
import { RefreshableAuthProvider, StaticAuthProvider } from 'twitch-auth';
import { ChatClient } from 'twitch-chat-client';

const singletonClient = new ChatClient(
  new RefreshableAuthProvider(new StaticAuthProvider('twitch_app_id', 'twitch_bot_access_token'), {
    clientSecret: 'valid_twitch_app_client_secret',
    refreshToken: 'valid_twitch_bot_refresh_token',
  }),
  {
    logger: { emoji: false, minLevel: 'DEBUG' },
  }
);

function postRegistration() {
  console.log('(after onRegister event) Succesfully logged into twitch chat')
  // @ts-ignore
  TwitchClient.client._credentials.password = 'oauth:eo9rptj24w1lnj2jgbadgimbz1yfol' // set any bad auth token right away, simulating an expired password
  // @ts-ignore
  TwitchClient.client._connection.assumeExternalDisconnect();
}

singletonClient.onRegister(postRegistration);
singletonClient.onAuthenticationFailure((msg) => console.warn(`(after onAuthenticationFailure event) Auth failure. msg: ${msg}`));
singletonClient.connect()
```

Here is some debug output of this happening:

```
[2020-11-02T05:40:55.786Z] ircv3 INFO Connecting to irc-ws.chat.twitch.tv:443
[2020-11-02T05:40:57.327Z] ircv3 INFO Connection to server irc-ws.chat.twitch.tv:443 established
[2020-11-02T05:40:57.327Z] ircv3 DEBUG Determining connection password
[2020-11-02T05:40:57.328Z] ircv3 DEBUG Sending message: CAP LS 302
[2020-11-02T05:40:57.355Z] ircv3 DEBUG Received message: :tmi.twitch.tv CAP * LS :twitch.tv/tags twitch.tv/commands twitch.tv/membership
[2020-11-02T05:40:57.357Z] ircv3 DEBUG Capabilities supported by server: twitch.tv/tags, twitch.tv/commands, twitch.tv/membership
[2020-11-02T05:40:57.357Z] ircv3 DEBUG Sending message: CAP REQ :twitch.tv/tags twitch.tv/commands
[2020-11-02T05:40:57.381Z] ircv3 DEBUG Received message: :tmi.twitch.tv CAP * ACK :twitch.tv/tags twitch.tv/commands
[2020-11-02T05:40:57.381Z] ircv3 DEBUG Successfully negotiated capabilities: twitch.tv/tags, twitch.tv/commands
[2020-11-02T05:40:57.382Z] ircv3 DEBUG Sending message: CAP END
[2020-11-02T05:40:58.343Z] ircv3 DEBUG Sending message: PASS oauth:[REDACTED]
[2020-11-02T05:40:58.344Z] ircv3 DEBUG Sending message: NICK [redacted_user]
[2020-11-02T05:40:58.344Z] ircv3 DEBUG Sending message: USER [redacted_user] 8 * :[redacted_user]
[2020-11-02T05:40:58.399Z] ircv3 DEBUG Received message: :tmi.twitch.tv 001 [redacted_user] :Welcome, GLHF!
[2020-11-02T05:40:58.399Z] ircv3 DEBUG Received message: :tmi.twitch.tv 002 [redacted_user] :Your host is tmi.twitch.tv
[2020-11-02T05:40:58.399Z] ircv3 DEBUG Received message: :tmi.twitch.tv 003 [redacted_user] :This server is rather new
[2020-11-02T05:40:58.400Z] ircv3 DEBUG Received message: :tmi.twitch.tv 004 [redacted_user] :-
[2020-11-02T05:40:58.400Z] ircv3 DEBUG Received message: :tmi.twitch.tv 375 [redacted_user] :-
[2020-11-02T05:40:58.400Z] ircv3 DEBUG Received message: :tmi.twitch.tv 372 [redacted_user] :You are in a maze of twisty passages, all alike.
[2020-11-02T05:40:58.400Z] ircv3 DEBUG Received message: :tmi.twitch.tv 376 [redacted_user] :>
(after onRegister event) Succesfully logged into twitch chat
[2020-11-02T05:40:58.473Z] ircv3 ERROR Disconnected unexpectedly
[2020-11-02T05:40:58.526Z] ircv3 INFO Disconnected
[2020-11-02T05:40:58.571Z] ircv3 INFO Connection to server irc-ws.chat.twitch.tv:443 established
[2020-11-02T05:40:58.572Z] ircv3 DEBUG Determining connection password
[2020-11-02T05:40:58.572Z] twitch-chat DEBUG Password assumed to be correct from last connection
[2020-11-02T05:40:58.572Z] ircv3 DEBUG Sending message: CAP LS 302
[2020-11-02T05:40:58.596Z] ircv3 DEBUG Received message: :tmi.twitch.tv CAP * LS :twitch.tv/tags twitch.tv/commands twitch.tv/membership
[2020-11-02T05:40:58.596Z] ircv3 DEBUG Capabilities supported by server: twitch.tv/tags, twitch.tv/commands, twitch.tv/membership
[2020-11-02T05:40:58.597Z] ircv3 DEBUG Sending message: CAP REQ :twitch.tv/tags twitch.tv/commands
[2020-11-02T05:40:58.619Z] ircv3 DEBUG Received message: :tmi.twitch.tv CAP * ACK :twitch.tv/tags twitch.tv/commands
[2020-11-02T05:40:58.619Z] ircv3 DEBUG Successfully negotiated capabilities: twitch.tv/tags, twitch.tv/commands
[2020-11-02T05:40:58.620Z] ircv3 DEBUG Sending message: CAP END
[2020-11-02T05:40:58.620Z] ircv3 DEBUG Sending message: PASS oauth:eo9rptj24w1lnj2jgbadgimbz1yfol
[2020-11-02T05:40:58.620Z] ircv3 DEBUG Sending message: NICK [redacted_user]
[2020-11-02T05:40:58.620Z] ircv3 DEBUG Sending message: USER [redacted_user] 8 * :[redacted_user]
[2020-11-02T05:40:58.655Z] ircv3 DEBUG Received message: :tmi.twitch.tv NOTICE * :Login authentication failed
(after onAuthenticationFailure event) Auth failure. msg: Login authentication failed
[2020-11-02T05:40:58.699Z] ircv3 INFO Disconnected
```

**Closed** 2020-11-19 21:39 UTC
Labels: bug
