### ISSUE TITLE
Allow to directly provide the webhook callback url

### ISSUE THREAD

**Issue by thomaslule** [d-fischer/twitch#119] opened 2020-04-01 20:41 UTC
## Feature Request

Hey 👋 

This is about the twitch-webhooks package.

I had a hard time figuring out what to put in the [WebHookListener.create options structure](https://d-fischer.github.io/twitch-webhooks/reference/interfaces/WebHookListenerConfig.html) in order to have the lib send the right callback url to twitch. It's not obvious what to put in the reverse proxy params to have the lib generate the right url.

I think it would be more straightforward to directly provide the url that will end up as `hub.callback` in the subscription request.

In my case, my inputs are: listening port + callback url so I even coded a thing that translates that to the structure (⚠️ may not work in all cases)

```typescript
  getCallbackProperties(listeningPort: number, callbackUrl: string) {
    const urlRegex = callbackUrl.match(
      /^(https?):\/\/([^/:]*)(:[0-9]+)?(\/.*)?$/
    );
    if (!urlRegex) {
      throw new Error(`Invalid callback url: ${callbackUrl}`);
    }
    const ssl = urlRegex[1] === "https";
    const hostName = urlRegex[2];
    const port = urlRegex[3]
      ? parseInt(urlRegex[3].substring(1), 10)
      : undefined;
    const pathPrefix = urlRegex[4] === "/" ? undefined : urlRegex[4];
    const behindProxy = ssl || pathPrefix || port !== listeningPort;
    const reverseProxy = behindProxy
      ? {
          ssl,
          pathPrefix,
          port: port ? port : ssl ? 443 : 80
        }
      : undefined;
    return {
      port: listeningPort,
      hostName,
      reverseProxy
    };
  }
```
(this is not pretty 😂 )

Anyway, you did a great work on those packages I'm amazed 👏 👏 👏

**Comment by d-fischer** [comment] 2020-04-01 20:51
There is already an effort to establish a more friendly way to pass the callback parameters at #109. Please add your feedback there.

Therefore closing this as a duplicate of said issue.

**Closed** 2020-04-01 20:51 UTC
