### ISSUE TITLE
Connection is not cleaned up even after quit is awaited on ChatClient

### ISSUE THREAD

**Issue by cheeseandcereal** [d-fischer/twitch#182] opened 2020-10-18 07:25 UTC
## Bug Report

https://github.com/d-fischer/twitch/commit/f5bbcc1129209fe2c877672512bf87b7dd949dd8#diff-f98b0f0baa72244a335359b25182fb3b256dbb6c04910e1c94f86c4681e81779R2076 introduced a bug where the disconnection promise when performing a quit is no longer returned. This makes it so that awaiting `quit` on an instance of `ChatClient` will not actually wait for the connection to be cleaned up before resolving. This can lead to issues with reconnections where a `connect` is attempted after an awaited `quit`.

**Comment by cheeseandcereal** [comment] 2020-10-18 09:03
I'm currently having issues with reconnection. Currently unclear if this is due to the above commit, or behavior that occurred before. Currently trying to get some consistent reproducible steps or at least turn up the log level and catch it when it happens to be able to provide some logs.

**Comment by d-fischer** [comment] 2020-10-18 19:44
Not waiting for the connection to clean up is intentional, since a disconnect can't be reliably determined.

The error or close events aren't ever fired when, for example, pulling out the physical ethernet cord.

Additionally, when I finally detect the ping timeout, I can call `.destroy()` on the socket, but it still never fires any event I know of.

The latest updates to this connection logic introduced this change and were thorougly tested for both software and hardware disconnects, and this isn't a problem. Reconnect attempts are being made and have no problems after I reconnect to the internet.

If there's an event I'm missing which reliably fires on a socket disconnect created by pulling the ethernet cord, please tell me.

For the time being, I'm going to close this as invalid.

If you can reproduce this error and track it to the above change, please comment here.
If you can reproduce this error and track it to somewhere else, please create a new issue.

**Closed by d-fischer** 2020-10-18 19:44 UTC
Labels: bug

**Comment by cheeseandcereal** [comment] 2020-10-18 20:43
It's definitely not reproduceable by just unexpectedly disconnecting by doing something like pulling a network cable; I tested that. I'm generally only seeing this issue after leaving it running for a a few days, and reconnection attempts just completely stop. I will report back when I can actually narrow down the root cause some more.
