### ISSUE TITLE
Make all Cheermote data available

### ISSUE THREAD

**Issue by AlcaDesign** [d-fischer/twitch#253] opened 2021-04-04 15:06 UTC
## Feature Request

I'd like to be able to get all of the Cheermote data from the API. My intended purpose is to be able to transform messages in a browser instead of through this package before it's sent. The data needs to be returned in an HTTP response because it can't be done in the browser. I can get the names of cheermotes but that doesn't include image URLs. In theory I could abuse `getCheermoteDisplayInfo` to squeeze out everything but that's not ideal.

**Comment by d-fischer** [comment] 2021-04-05 01:30
Closing as dupe of #233.

**Closed** 2021-04-05 01:30 UTC
Labels: feature
