### ISSUE TITLE
ChatClient.isConnected never turns to false on lose of internet

### ISSUE THREAD

**Issue by billygerhard** [d-fischer/twitch#169] opened 2020-09-03 10:13 UTC
## Bug Report

chatClient.isConnected never toggles to false when it looses internet connection. I tested by pulling my Ethernet cable to force an internet loss, and it stayed as true. Tt is false before I use .connect(), so it is right on initialization, and once it connects, but then just never updates.

### Code

```ts
let twitchChatClient = ChatClient.anonymous({requestMembershipEvents:true});
await twitchChatClient.connect();
```

### Expected behavior

Whenever the socket looses connection, the boolean should swap to false.

### Actual Behavior

Stays as true.

### Environment

- Version: 4.2.0-pre.7
- Browser version: Chrome 85.0.4183.83 
- Operating system: Win 10

**Comment by d-fischer** [comment] 2020-09-19 21:07
Does this have any unavoidable impact right now? Otherwise I'll get it into 4.3 only because I have to refactor some of the chat connection parts again anyway.

**Comment by billygerhard** [comment] 2020-09-19 22:14
It’s not a show stopper. I use it to show the status on like a dashboard. So it won’t let the user know it’s not connected. But the auto reconnect even after having the cord unplugged seemed to work flawlessly.

**Comment by d-fischer** [comment] 2020-10-01 23:37
Possibly also fixed by the changes I made in 4.3.0-pre.0 to fix #161. Please try to reproduce it again with this version.

**Comment by billygerhard** [comment] 2020-10-06 18:12
This was fixed when you let the session timeout with no response to Ping, but it does not disappear as soon as the websocket is disconnected. It could take a minute to determine that the chat bot is no longer connected.

**Comment by d-fischer** [comment] 2020-10-06 19:29
Alright, closing this for now. I may adapt the default ping timers in the future.

**Closed by d-fischer** 2020-10-06 19:29 UTC
Labels: bug
